"""update images path migration

Revision ID: 274aa3633393
Revises: efbf910cba0c
Create Date: 2022-05-11 10:05:36.961152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274aa3633393'
down_revision = 'efbf910cba0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###
