"""update database features migration

Revision ID: e482c8d3a6ac
Revises: ec7021393449
Create Date: 2022-05-11 14:28:09.668555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e482c8d3a6ac'
down_revision = 'ec7021393449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'pitch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pitches', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('pitches', 'post',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('pitches', 'category',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitches', 'category',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('pitches', 'post',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('pitches', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('comments', 'pitch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
